### ISSUE TITLE
DSL Markers in maven plugin?

### ISSUE THREAD

**Issue by asad-awadia** [marcoferrer/kroto-plus#26] opened 2019-02-01 04:17 UTC
How do you use `use_dsl_markers` in ProtoBuildersGenOptions via maven?

**Comment by marcoferrer** [comment] 2019-02-18 13:48
Which protoc plugin artifact are your using? `protoc-gen-grpc-coroutines` or `protoc-gen-kroto-plus`? Only the kroto-plus artifact with support the `use_dsl_markers` option. To enable it, confirm your kroto config path is being set correctly in maven.

```xml
<execution>
            <id>kroto-plus</id>
            <goals>
                <goal>compile-custom</goal>
            </goals>
            <configuration>
                <pluginId>kroto-plus</pluginId>
                <pluginArtifact>com.github.marcoferrer.krotoplus:protoc-gen-kroto-plus:${krotoPlusVersion}:jar:jvm8</pluginArtifact>
                <pluginParameter>ConfigPath=${project.basedir}/krotoPlusConfig.asciipb</pluginParameter>
            </configuration>
        </execution>
```

Then in `krotoPlusConfig.asciipb`, inside your `proto_builders` configuration, set the flag.
asciipb
```
proto_builders {
    ....
    use_dsl_markers: true
}
```
json
```
"protoBuilders": [
     {
         .....,
         "useDslMarkers": true
     }
]
```

Another important note is that the `use_dsl_markers` option relies on the protoc-insertions feature.
So the output directory of both `protoc-gen-kroto-plus` and `protoc-gen-java` must match.

Im not 100% familiar with all the configuration options for the protobuf maven plugin, but a quick google search shows the options might be 
```xml
<configuration>
    <pluginId>kroto-plus</pluginId>
    <pluginArtifact>com.github.marcoferrer.krotoplus:protoc-gen-kroto-plus:${krotoPlusVersion}:jar:jvm8</pluginArtifact>
    <pluginParameter>ConfigPath=${project.basedir}/krotoPlusConfig.asciipb</pluginParameter>
    <outputDirectory>${basedir}/target/generated-sources/path/to/java/output</outputDirectory>
</configuration>
```

**Comment by marcoferrer** [comment] 2019-02-20 02:46
I had some time to fully dig into this and found the source of the issue. The protobuf maven plugin doesnt fully support the protoc insertions api and the moment. My findings are documented [here](https://github.com/marcoferrer/kroto-plus/issues/28#issuecomment-465397558)

**Comment by marcoferrer** [comment] 2019-04-08 23:27
Closing as a duplicate of #28

**Closed by marcoferrer** 2019-04-08 23:27 UTC
